version: "3.9"

services:
  kali:
    build: .
    container_name: kali_lab
    ports:
      - "6080:6080"
      - "5901:5901"
    volumes:
      - kali_data:/home/kali
    restart: unless-stopped

volumes:
  kali_data: